### ISSUE TITLE
Feature request: sync vanilla worldborder with CB border

### ISSUE THREAD

**Issue by Over2Craft-mc** [pop4959/ChunkyBorder#10]
Vanilla worldborder has the advantage of being more aesthetic and more ergonomic for players but has the disadvantage of not beeing safe (spectator gamemode can pass trough for example).

Adding an option per border to synchronize the vanilla one with the CB one would be nice. This option would probably only works on border with a square shap

**Comment by pop4959** [comment]
@Over2Craft-mc Latest dev builds have the border configuration `sync-vanilla` which will sync the vanilla world border with CB when added (aka will not apply to borders added prior to setting this to true).

**Comment by Kocimietka7192** [comment]
Unfortunately, there is no longer this option, why?

**Comment by pop4959** [comment]
> Unfortunately, there is no longer this option, why?

This was replaced with the `chunky worldborder` and `chunky border add` commands, which can be performed easily per-world.

The config option was hardly ever used and caused more problems and confusion than it fixed.
