### ISSUE TITLE
Issue with World Border disappearing with multiple worlds

### ISSUE THREAD

**Issue by ejmason101** [pop4959/ChunkyBorder#11]
Wonder addition to chunky!

I just recently added multiverse to add a creative world to our survival server. I can add borders to both worlds, but eventually either the survival, creative, or both worlds will have the chunkyborder dropped.

Nothing in logs or anything shows that it is dropping the WB due to an error, was wondering if anyone had run into these issues before.

**Comment by pop4959** [comment]
More details would be appreciated. For example, what version of both plugins are you running? Are you using a map (if so, which & what version)? Are the borders being "dropped" just on the map, or are players able to physically pass a border?

Lastly, is the issue only occurring in the Multiverse worlds?

**Comment by ejmason101** [comment]
Chunky-1.1.21
ChunkyBorder-1.0.4
Spigot 1.16.4
Multiverse-Core-4.2.2

I know when a border drops because both the survival world and the creative superflat will lose their WB, the dynmap will no longer show the border, and normal players are able to go past the bounds where the WB usually is.  So it is both dropping from the map and players are able to physically pass a border.

We are running a survival vanilla world, with one multiverse portal to a creative world where server members can test out designs. Before adding multiverse and setting a second world border on the creative world, the border never disappeared and we had no problems. 

I think the root of this has to do with multiverse, but **I will update both the plugins to the most recent version (duh on my part, should have done that before dropping an issue here)** and report back if we see the borders drop in the next couple days again. I do not know the amount of time that elapses or if it is related to server reboots but will keep a close eye and report on that here later as well.

**Comment by ejmason101** [comment]
After updating the two jars and rebooting, it looks like both the borders in the survival and creative world came back and are active.. 
I am going to go ahead and close this chalking up to outdated versions and if the WB's drop again for no reason I will open again!

**Comment by pop4959** [comment]
No problem, thanks for updating! There were a few changes made since 1.0.4 which should help a lot with Multiverse compatibility, especially when it comes to worlds being loaded or unloaded after initial server startup. So hopefully you should not experience this issue again. Though if it does happen, please do re-open and let's figure it out.
