### ISSUE TITLE
Console Spam with SVIS Integration

### ISSUE THREAD

**Issue by mercurialmusic** [pop4959/ChunkyBorder#16]
Unsure if this is something for you or something SelectionVisualizer needs to update but I'm posting in both places just in case. Started getting some pretty significant console spam after the update to ChunkyBorder 1.0.38 (SVIS hadn't at the time made any changes). Spam shows up regardless of whether the SVIS integration is enabled. Looks like it's due to CB's changes to the center point of the border.

**ERROR:** https://gist.github.com/mercurialmusic/96ea289df3b0e1353137a77dfc32247b

**Server Type (Spigot/Paperspigot/etc):** Paper
**Server Version:** git-Paper-777 (MC 1.16.5) on Java 16

**Relevant plugins:** [SelectionVisualizer 3.0.4.0](https://www.spigotmc.org/resources/selection-visualizer.22631/)

Thanks!

**Comment by pop4959** [comment]
Thanks; looks like this is a problem with Selection Visualizer's integration. I've commented on your other issue with details which should help them update it. Till then, you may wish to run the previous version of Chunky/Border on your server (which should work fine on 1.17, but does not contain any new features).

**Comment by mercurialmusic** [comment]
Thanks!
