### ISSUE TITLE
Introduce a /chunkyborder bypass command

### ISSUE THREAD

**Issue by baailey** [pop4959/ChunkyBorder#17]
Hi, recently switching from WorldBorder and I've noticed that the only way to allow someone to bypass the border is by giving them the permission. I feel introducing a command to toggle bypass for yourself and others could be much more convenient. The two commands could be: 

- `/chunkyborder bypass` 
- `/chunkyborder bypass [player]`

This can 1. Allow toggling whether you yourself will bypass the border (personally, I only wish to bypass the border for specific circumstances, and I'd prefer not giving myself the permission every time) and 2. Toggle whether a specific user can bypass the border. This will prevent having to give them the bypass permission, and makes the process easier overall.

I believe the first command can be introduced via the `chunkyborder.bypass.move` permission, and the second one can potentially be a permission like `chunkyborder.bypass.move.others`, for example. But it may be easier to just make a separate permission entirely.

**Comment by pop4959** [comment]
If this is added it would probably be only for a temporary bypass rather than permanent. The whole reason we moved to a permission is because it makes much more sense for something like this to be one, and I'm not sure why WorldBorder never did that to begin with (most likely because permission plugins didn't exist / weren't established enough at the time, it's old).

**Comment by pop4959** [comment]
Added in 9264dede38b699fcaff2ff6490d2bccd17b2743e. There aren't specific permissions for the command, but there aren't for any other commands either yet. Though, hopefully this isn't too big of a deal for you right now (if it is, I guess that's the next thing I can work on 😛).

You can grab the latest build here [https://ci.codemc.io/view/Author/job/pop4959/job/ChunkyBorder/](https://ci.codemc.io/view/Author/job/pop4959/job/ChunkyBorder/)
