### ISSUE TITLE
(Suggestion) Update config.yml documentation

### ISSUE THREAD

**Issue by Oaksworth** [pop4959/ChunkyBorder#23]
Hello!

This is a suggestion to update the `config.yml` documentation on the [wiki](https://github.com/pop4959/ChunkyBorder/wiki/Configuration) to include the following options:

- `prevent-enderpearl`
- `sync-vanilla`
- `map-options` → `enable` → `pl3xmap`

**Comment by pop4959** [comment]
Updated :)
