### ISSUE TITLE
(Bug) The border's colour cannot be changed for Dynmap

### ISSUE THREAD

**Issue by Orenji64** [pop4959/ChunkyBorder#33]
The parameter that sets the colour of the border in the config does not change anything and the border stays red on the map.
```yml
...
# The hexadecimal color code of the world border shown on the map.
# For help with this, visit a site like https://www.color-hex.com/
color: FF0000
...
```
Using Dynmap on Paper 1.18 with the latest version of Chunky and ChunkyBorder.
There are no console errors during startup relating the either plugin.

**Comment by pop4959** [comment]
Unable to produce this on Chunky 1.2.153 + ChunkyBorder 1.0.59 + Dynmap v3.3-beta-1.

Let me know if you have more specific steps which cause the issue, but otherwise I would recommend double checking that you've saved the configuration and have restarted the server for the changes to take effect.

**Comment by pop4959** [comment]
There is also the [Discord support server](https://discord.gg/ZwVJukcNQG) if you want to share your configuration for me to take a look.
