### ISSUE TITLE
Wrong teleport back

### ISSUE THREAD

**Issue by Hikk0o** [pop4959/ChunkyBorder#38]
Hello!

If you eat chorus near the nether border, player teleports over bedrock.

![2022-01-24_14 37 30](https://user-images.githubusercontent.com/78872275/150776259-054a58cb-d885-4b8a-9ba5-8aed7af3ca69.png)
![2022-01-24_14 37 34](https://user-images.githubusercontent.com/78872275/150776266-bf31da08-8cb0-424c-b974-44c8458218b1.png)

**Comment by pop4959** [comment]
Hmmmm, yeah that doesn't look ideal. Does it always teleport you to the roof of the nether, or does it sometimes find a safe spot underneath?

**Comment by Hikk0o** [comment]
> Hmmmm, yeah that doesn't look ideal. Does it always teleport you to the roof of the nether, or does it sometimes find a safe spot underneath?

Based on my observations, always (I tried 5-6 times)

**Comment by pop4959** [comment]
Hey, long time, I finally got around to revisiting this and decided that the best choice here would be to add a configuration option to disable this mechanic near the border.

Once you've updated to a new version, just set `prevent-chorus-fruit: true` in the config.yml.

Chorus fruit will work normally when not near the border, but they will not teleport you if the teleport would cause you to go over the border, similar to the ender pearl option.

**Comment by pop4959** [comment]
I've made another adjacent change, though it still doesn't match chorus fruit behavior exactly. See #44 for details.
