### ISSUE TITLE
Feature request: active world

### ISSUE THREAD

**Issue by SlimeDog** [pop4959/ChunkyBorder#4]
Presently, one needs to use `chunky world <world>` to change to the current world (unless the current world is `world`). This is rather non-intuitive. Please consider making the active world for all commands the current world, unless it has been explicitly set with `chunky world <world>`.

See related Chunky feature request: https://github.com/pop4959/Chunky/issues/53

**Comment by pop4959** [comment]
Thanks again for the feature request, although unfortunately I will be closing this for the reasons described in the linked issue.
