### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by bumbummen99** [pop4959/ChunkyBorder#43]
Simple: Plugin is built against Version X of Chunky for all available versions of minecraft. That does lead to the current version of this plugin require a version of chunky that does not exist for 1.18.2.

**Comment by bumbummen99** [comment]
apparently can't read

**Comment by bumbummen99** [comment]
Ok i am not insane, Curseforge does display the plugin available for 1.18.2 but Chunky has not been released in that version for 1.18.2

**Comment by pop4959** [comment]
This was an oversight, I was working on the port of ChunkyBorder to Fabric during 1.18, and it was only released after 1.19 came out. The builds of Chunky that are compatible with ChunkyBorder for 1.18 are not posted to CurseForge.

At this time I do not plan on making another release build for 1.18. The development builds that currently have support for ChunkyBorder should work just fine, but current release builds target 1.19. I just don't really have the spare time to backport all changes made in newer versions of Minecraft to older versions.

Thanks anyways for the heads-up! Perhaps I'll add a note on the project page if enough people are confused about it.
