### ISSUE TITLE
Make visualiser only show particles to target player

### ISSUE THREAD

**Issue by illumeleet** [pop4959/ChunkyBorder#46]
title

**Comment by pop4959** [comment]
Not enough information here, can you elaborate?

What is the issue you are experiencing with this feature?

How do you propose solving it?

**Comment by illumeleet** [comment]
You are able to see other player's border visualisation
![image](https://user-images.githubusercontent.com/51333325/187048214-ae949643-0c84-44d3-bbb2-907baa3c32a2.png)
I propose to draw particles to player instead of world:
`particleLocations.forEach(location -> bukkitPlayer.spawnParticle(Particle.REDSTONE, new org.bukkit.Location(bukkitWorld, location.getX(), location.getY(), location.getZ()), 1, visualizerOptions));`

**Comment by pop4959** [comment]
Oh, I see. Yeah alright, that's a bug. I thought you were asking for an option to only allow certain players to see the border, or something of the sort. Gotcha.

**Comment by pop4959** [comment]
Fixed! Thanks for reporting 😃
