### ISSUE TITLE
Feature request: y axis range limit

### ISSUE THREAD

**Issue by Pantera07** [pop4959/ChunkyBorder#50]
Currently, ChunkyBorder can only limit the x z axis range.
I suggest adding an option to limit the y axis range.

This would be useful for nether roof etc.

**Comment by pop4959** [comment]
Sorry for the long response time. There isn't an option, but it does look like the logical world height is already considered as part of the teleportation. You shouldn't be teleported onto the nether roof. If this is still an issue for you, please open a new bug report.
