### ISSUE TITLE
Globe Wrapping

### ISSUE THREAD

**Issue by Mint-101** [pop4959/ChunkyBorder#51]
This is kind of a niche but for those who run earth servers it would be nice if there was a way to make the wrap work so that you are traveling across the globe. Kind of hard to describe so here is a picture to better explain what I am talking about. 
![image](https://user-images.githubusercontent.com/49204037/214189859-6f1ed87f-f3fe-4e56-85cb-751b6c77877f.png)
As you can see If I cross the world border at Antarctica in the west, I should be teleported to a parallel spot on the border in the east. It's fine if you do not feel like implementing this feature as your resources might be better spent elsewhere. Just wanted to get this idea out there.

**Comment by pop4959** [comment]
This should already be implemented as per https://github.com/pop4959/ChunkyBorder/issues/45.

You should be able to access it by changing the wrap type to "earth".
