### ISSUE TITLE
Feature request: Suggestions for coordinates

### ISSUE THREAD

**Issue by seema84** [pop4959/ChunkyBorder#53]
Maybe is a suggestions for coordinates at tab completion as in the vanilla commands a think.
In Vanilla, the coordinates you look at are used as a suggestion. However, this could lead to decimal numbers. 
Maybe this is useful for some people.

**Comment by pop4959** [comment]
I don't really have plans for adding this currently, especially considering the "center on player" functionality was since added which is close enough, and I haven't even seen many people use that.
