### ISSUE TITLE
Add a feature to prevent block physics or water flow.

### ISSUE THREAD

**Issue by Radiation-pi** [pop4959/ChunkyBorder#55]
Please add a feature to prevent the physics out of the border. The water flow outside of the world may lag the server and it's inaesthetic.
Thx for your plugins coding!

**Comment by pop4959** [comment]
Hi, thanks for the suggestion! Unfortunately fixing that kind of thing is not something that Chunky Border is created for. To pre-generate chunks, use Chunky instead! Pre-generating chunks with a chunk unload delay should allow post generation to occur which will settle physics/liquids in the world. If you have any questions please join the chunky support channel on our [Discord server](https://discord.gg/ZwVJukcNQG).
