### ISSUE TITLE
Folia

### ISSUE THREAD

**Issue by Alienn-Know** [pop4959/ChunkyBorder#57]
suggest adding support Folia
![2023-05-07_00 15 18](https://user-images.githubusercontent.com/48494466/236646841-04ffe293-f7f2-4373-a129-5a2c25184039.png)

**Comment by pop4959** [comment]
I have not had time to look into supporting Folia in this plugin yet.

PRs welcome if anyone would like to give it a shot, it may not actually be all too much work.

**Comment by MineSunshineone** [comment]
i also need it

**Comment by pop4959** [comment]
Added in 06c6d345f73b242a704fced445874525786e899d
