### ISSUE TITLE
Feature request: list command

### ISSUE THREAD

**Issue by SlimeDog** [pop4959/ChunkyBorder#6]
Please consider adding `cb list <world>` command to report border constraints in current world or named world.

**Comment by pop4959** [comment]
I was actually just thinking this tonight. Definitely planning to add this.

**Comment by SlimeDog** [comment]
and `cb listall` I suppose. Useful at the console.

**Comment by SlimeDog** [comment]
Looks good in CB 1.0.6
Thanks.
