### ISSUE TITLE
[Question/Request] Cancel generating Chunks behind ChunkyBorder Border

### ISSUE THREAD

**Issue by SkyKingPX** [pop4959/ChunkyBorder#67]
Hello,
I have the question, if chunks behind the World Border are still being generated if someone is near the border.
If not I would like to know if it is possible to add that.

Thanks.

**Comment by pop4959** [comment]
It is not possible to cancel chunk generation behind the border. Set your border size accordingly, take other actions such as installing a void generator plugin (to generate air there) or setting the player's view distance low enough to not generate chunks.

If you are using a web map you can also utilize the visibility limits feature to prevent the map from displaying chunks past the border. You might need to re-render the map afterward.
