### ISSUE TITLE
TELEPORTING

### ISSUE THREAD

**Issue by HonzasikCZ** [pop4959/ChunkyBorder#71]
When I go to the worldborder, it takes me to the other part of the map, for example from the coordinates 29999 63 0 to -29999 63 2, so it's not that I'm completely on the other part of the map, but I'm also outside the worldborder where I can move freely

I hope it will be resolved
I wish you a nice rest of the day!

**Comment by pop4959** [comment]
Hi this does not sound like a bug. It sounds like you have wrap enabled for your world border.

If you are still having issues, consider joining our [Discord server](https://discord.gg/ZwVJukcNQG) for help troubleshooting.
