### ISSUE TITLE
Allow borders to be reloaded in the reload command

### ISSUE THREAD

**Issue by TomLewis** [pop4959/ChunkyBorder#72]
Wanted to quickly move over some borders from creative to survival, copy/paste the borders I need and chunky reload.. nope! not showing in /chunky borders list :(

**Comment by pop4959** [comment]
Yeah it looks like this only reloads the config right now and not the borders. I'll see if we can change that.

**Comment by TomLewis** [comment]
Awesome

**Comment by pop4959** [comment]
This has been added in abc4173b4595edd8aeb31f8d4a4cdd18f6d3ac21.

The reload is performed through `/chunky reload`.
