### ISSUE TITLE
Update Chunk Border for 1.21 (paper)

### ISSUE THREAD

**Issue by globau** [pop4959/ChunkyBorder#74]
With Chunky 1.4.16 adding 1.21 support (🎉), it would be nice for Chunky Border to get the same treatment.

From my experiments it appears to work without issue under 1.21, so it's likely that all that's needed is an update of the metadata on Modrinth.

Thanks!

**Comment by pop4959** [comment]
Hi, it looks like the 1.21 versions are already uploaded on Modrinth. Is there a specific version you are having an issue with?

**Comment by globau** [comment]
Sorry, should have mentioned this is for Paper, which is still showing as only compatible with 1.20.5 and 1.20.6

**Comment by pop4959** [comment]
If I understand you correctly you just wanted me to tag this. Done!

If you are having any other issues with the release please let me know. Thanks.

**Comment by globau** [comment]
Perfect, ty!

**Comment by pop4959** [comment]
No worries! I was confused at first, but I didn't see I missed that version. I updated the tags in most other places.

Generally speaking the Bukkit/Paper version doesn't require updates for new Minecraft releases as the API is much more stable, it's mostly the modded platforms for Fabric/Forge that require some changes.

**Comment by globau** [comment]
For context I have automation that makes use of the Modrinth API to check for new versions, and it was sad that there wasn't a paper version tagged as 1.21 compatible.

Some plugins broke with 1.21 mostly around the deprecation of `Material` that Paper's pushing on, so in general I prefer to run plugins "within spec" (getting a spec update where required, as is the case here).
