### ISSUE TITLE
Add wrap feature

### ISSUE THREAD

**Issue by TenReeez** [pop4959/ChunkyBorder#8]
Add the wrap command and feature to enable players to be tp'd to other side of map.  When they reach a world border.

If possible on a square bordered world add a feature where players only get tp'd when they reach the x cord borders. (more realistic) but that is not a necessity. 

Thank you

**Comment by pop4959** [comment]
@TenReeez Added in the latest version, which you can find [here](https://ci.codemc.io/view/Author/job/pop4959/job/ChunkyBorder/17/) for now (will be uploaded to Spigot later).

To use, simply add the border (or select the world for the current one), and type `chunkyborder wrap` to toggle wrapping for that border.
